cfg:
  filters: [128, 192, 256]
  divns: [2, 2, 2]
  overall_dropout: 0.4
  dropout_rate: [0.1, 0.1, 0.1]
  init_lr: 5e-4
  batch_size: 152
  test_size: 0.1
  epochs: 200
dataset_name: "SVHN"
num_classes: 10
input_shape: [3, 32, 32]
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
log_pth: "logs/svhn"